baseURL: https://tanishayadav.netlify.app/
languageCode: en-us
title: Tanisha Yadav
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my website. I'll be sharing a little bit about myself and a lot about my work
    title: Hi, My name is Tanisha 
  blog: {}
  contact:
    address:
      - city: London, ST NW1 5AH
        country: United Kingdom
        street: Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tyadav.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7880333618
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/tayadav
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/tanisha-yadav-04b27817b/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: IMG_6654_Original.jpg
        subtitle: MAM'22, London Business School  
        title: Who am I  
        url: blogs/tanisha
      - image: connected world.jpg
        subtitle: Insta or Snap 
        title: Connected World
        url: blogs/tempus
      - image: biden.jpg
        subtitle: Biden's Popularity
        title: Joe Biden
        url: blogs/magna
      - image: worldhappiness.jpg
        subtitle: Happiness Report
        title: World Happiness 
        url: blogs/ipsum
      - image: smoking.jpg
        subtitle: Impact on Babies 
        title: Pregnancy and Smoking
        url: blogs/consequat
      - image: drinks.jpg
        subtitle: Top 25
        title: Beer, Wine & Spirits
        url: blogs/etiam
  #two:
    #buttonText: Get Started
    #enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      #\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      #condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      #pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      #Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      #amet pharetra et feugiat tempus."
    #title: Massa libero
    #url: blogs
